### ISSUE TITLE
build failing (sudo needed) - "add bridge failed: Operation not permitted"

### ISSUE THREAD

**Issue by mjbright** [includeos/includeos-docker-images#14]
First outing trying to build these images, I'm getting a permissions error on the first build.

`docker build -t includeos/includeos-common:0.10.0.1 -f Dockerfile.common .`

Produces:
`...
>>> Done! IncludeOS bundle downloaded and installed

>>> Creating network bridge for IncludeOS
>>> Using default settings
>>> Creating bridge bridge43, netmask 255.255.0.0, gateway 10.0.0.1
>>> Creating network bridge (requires sudo):
add bridge failed: Operation not permitted
-e >>> Sorry <<<
Could not create or configure bridge.

The command '/bin/sh -c cd ~ && pwd &&   cd IncludeOS &&   ./install.sh -n' returned a non-zero code: 1
`

I'm building this on Ubuntu 16.04.3 LTS, with docker 17.09.0-ce
(I also tried with the stock  docker 1.12.6 from the Ubuntu repos).

**Comment by mnordsletten** [comment]
Hi, thanks for creating the issue. This is indeed an error. 

This is happening because the default in these docker images is the version 0.10.0.1 of IncludeOS. That version of IncludeOS tries to install a network bridge which is not supported in the docker build step.

What you can do is to build a newer version of the operating system by using the command:
```
docker build -t includeos/includeos-common:dev --build-arg TAG=v0.11.0-rc.2 -f Dockerfile.common .
```
Or you can build the newest dev version of IncludeOS by using the tag: `dev`

Both of these are available from the docker hub: https://hub.docker.com/r/includeos/includeos-common/tags/

I will update the dockerfile to use a newer version of IncludeOS so that it will build.

**Comment by mjbright** [comment]
Thanks a lot Martin, that did the trick.
